### ISSUE TITLE
/Storage report

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin3#28]
The idea is to show, for each camera the storage being used.

Idea 1: the columns are Months, e.g.  JFMAMJJASOND and each month is X or - . 

We would start with all construction and old-construction and show for all time.

m

**Comment by ijunaid8989** [comment]
This needs a lot of brainstorming before jumping into it. 
Right now.

First write a script, which will
  - run each day
  - save for all construction cameras
  - save for a camera exid, against one year. 

or we need to do it for hours per day, instead of months but am not sure, 

/cc @azharmalik3 for more ideas,

**Comment by ijunaid8989** [comment]
Storage report has been added https://admin.evercam.io/storage

Kind of working as well.

any other remarks could make it better if you have any. otherwise its complete.

**Comment by marcoherbst** [comment]
Closing This. Well done.
